#!/bin/sh

# To use:
#  - update the dir path/file name pattern 
#  - to have the file names/error message on the screen:
#     $ wgrib2_find_bad
#  - to pipe the file names/error message to a file:
#     $ wgrib2_find_bad > /lfs/h1/nco/stmp/ying.lin/find.out 2>&1

cd /lfs/h1/ops/prod/dcom/20230131/wgrbbul/cmcens_gb2
for file in `ls 2023013100_CMC_naefs_hr_latlon0p5x0p5_P*_*.grib2`
do
  echo $file
  wgrib2 $file > /dev/null
done

